# Generated by Django 5.0.3 on 2024-04-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='이름')),
                ('user_phone', models.CharField(max_length=20, verbose_name='전화번호')),
            ],
        ),
    ]
