# Generated by Django 5.0.3 on 2024-04-16 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chinese', '0002_food_image_url'),
        ('customer', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Chinese.category'),
        ),
    ]
