# Generated by Django 5.0.3 on 2024-04-15 17:17

import Chinese.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='음식 이름')),
                ('description', models.CharField(default='', max_length=500, verbose_name='음식 설명')),
                ('price', models.IntegerField(default=0, verbose_name='음식 가격')),
                ('image', models.ImageField(upload_to=Chinese.models.Food.get_image_path)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Chinese.category')),
            ],
        ),
    ]
