# Generated by Django 5.0.3 on 2024-04-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chinese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
